version: '3'

volumes:
  chatApp_mongo: {}
services:
   mongo:
    image: mongo:4.4.3-bionic
    restart: always
    ports:
      - 27017:27017
    volumes:
      - chatApp_mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: danny101201
      MONGO_INITDB_ROOT_PASSWORD: Kjhg2365987